app/urls.py
from django.urls import path, include
from app import views

app_name = 'app'

urlpatterns = [
    # path('login/', views.Login.as_view(), name="login"),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('upload/', views.UploadImage.as_view(), name="upload"),
    path('base/', views.ShowImages.as_view(), name="base"),
    path('delete/<img_id>', views.DeleteImage.as_view(), name="delete"),
    path('filter/<img_id>', views.FiltersChoice.as_view(), name="filter"),
    path('choice/<img_id>', views.FiltersChoice.as_view(), name="choice"),
    path('likes/<img_id>', views.Likes.as_view(), name="likes"),
    path('comment/<img_id>', views.Comments.as_view(), name="comment"),
    path('most_like/', views.MostLikes.as_view(), name="most_like"),
    path('most_comments/', views.Mostcomments.as_view(), name="most_comments"),
]

biopic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class ImagePostModel(models.Model):
    caption = models.CharField(max_length=200)
    image = models.ImageField(upload_to="app/static/app/photos/")
    uploaded_by = models.CharField(max_length=20, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def image_url(self):
        return self.image.name[len('app/static/'):]


class Comments(models.Model):
    comment = models.CharField(max_length=180)
    time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(ImagePostModel, on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

app/forms.py
from django import forms
from PIL import Image, ImageFilter
from app.models import ImagePostModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImagePostModel
        fields = ('uploaded_by', 'image', 'caption')


class Filters(forms.Form):
    choice = {
        'BLUR': 'Blur',
        'CONTOUR': 'Contour',
        'DETAIL': 'Detail',
        'EDGE_ENHANCE': 'Edge Enhance',
        'EDGE_ENHANCE_MORE': 'Edge Enhance More',
        'EMBOSS': 'Emboss',
        'FIND_EDGES': 'Find Edges',
        'SMOOTH': 'Smooth',
        'SMOOTH_MORE': 'Smooth More',
        'SHARPEN': 'Sharpen'
    }
    Filter_Choice = forms.ChoiceField(choices=(choice.items()))

    def filters(self):
        return {
            'BLUR': ImageFilter.BLUR,
            'CONTOUR': ImageFilter.CONTOUR,
            'DETAIL': ImageFilter.DETAIL,
            'EDGE_ENHANCE': ImageFilter.EDGE_ENHANCE,
            'EDGE_ENHANCE_MORE': ImageFilter.EDGE_ENHANCE_MORE,
            'EMBOSS': ImageFilter.EMBOSS,
            'FIND_EDGES': ImageFilter.FIND_EDGES,
            'SMOOTH': ImageFilter.SMOOTH,
            'SMOOTH_MORE': ImageFilter.SMOOTH_MORE,
            'SHARPEN': ImageFilter.SHARPEN
        }.get(self.cleaned_data['Filter_Choice'], None)


class CommentForm(forms.Form):
    comment = forms.CharField(max_length=50)

    def __init__(self, post=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.post = post

    def save(self):
        return self.post.comments_set.create(
            comment=self.cleaned_data['comment'])


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username', 'birth_date', 'password1', 'password2', )

app/views.py
from django.shortcuts import render, redirect
from PIL import Image, ImageFilter
from django.views import View
from app.forms import *
from app.models import ImagePostModel
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

# Create your views here.


class UploadImage(View):
    def get(self, request):
        form = ImageUploadForm()
        return render(request, 'app/upload.html', {'form': form})

    def post(self, request):
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            caption = form.cleaned_data['caption']
            image = form.cleaned_data['image']
            uploaded_by = form.cleaned_data['uploaded_by']
            ImagePostModel(
                caption=caption, image=image, uploaded_by=uploaded_by).save()
            return redirect("app:base")
        else:
            return render(request, 'app/upload.html', {'form': form})


class ShowImages(View):
    def get(self, request):
        objects = ImagePostModel.objects.all().order_by('-uploaded_at')
        return render(request, 'app/base.html',
                      {'objects': objects,
                       'c_form': CommentForm()})


class DeleteImage(View):
    def post(self, request, img_id):
        ImagePostModel.objects.get(id=img_id).delete()
        return redirect('app:base')


class FiltersChoice(View):
    def get(self, request, img_id):
        form = Filters()
        return render(request, 'app/filter.html', {'form': form})

    def post(self, request, img_id):
        form = Filters(request.POST)
        path = 'app/static/' + ImagePostModel.objects.get(
            id=img_id).image_url()
        image = Image.open(path)
        if form.is_valid():
            filter_choice = form.filters()
            image.convert('RGB').filter(filter_choice).save(path)
            return redirect("app:base")
        else:
            return render(request, 'app/filter.html', {'form', form})


class Likes(View):
    def post(self, request, img_id):
        count = ImagePostModel.objects.get(id=img_id)
        count.likes += 1
        count.save()
        return redirect('app:base')


class Comments(View):
    def post(self, request, img_id):
        document = ImagePostModel.objects.get(id=img_id)
        form = CommentForm(document, request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:base')
        else:
            return redirect('app:base')


class MostLikes(View):
    def get(self, request):
        objects = ImagePostModel.objects.all().order_by('-likes')[:4]
        return render(request, 'app/most_like.html', {'objects': objects})


class Mostcomments(View):
    def get(self, request):
        objects = ImagePostModel.objects.all().order_by('-comments')[:3]
        return render(request, 'app/most_comments.html',
                      {'objects': objects,
                       'c_form': CommentForm()})


class Signup(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'app/signup.html', {'form': form})

    def post(self, request):
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.refresh_from_db(
                )  # load the profile instance created by the signal
                user.profile.birth_date = form.cleaned_data.get('birth_date')
                user.save()
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(
                    username=user.username, password=raw_password)
                login(request, user)
                return redirect('app:base')
        else:
            form = SignUpForm()
        return render(request, 'app/signup.html', {'form': form})

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django View Practice</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <center>
        <div id=header>
            <img src="../../static/app/logo/FullSizeRender.png" />
        </div>
        <form action="{% url 'app:upload' %}">
            <button>
                <i class="fa fa-upload" aria-hidden="true"></i> Upload Image
            </button>
        </form>
        <br>
        <form action="{% url 'app:most_like' %}">
            <button>
                <i class="fa fa-heart" aria-hidden="true"></i> Most Likes
            </button>
        </form>
        <br>
        <form action="{% url 'app:most_comments' %}">
            <button>
                <i class="fa fa-comments" aria-hidden="true"></i> Most Comments
            </button>
        </form>
        <br>
    </center>
    {% if objects %} {% for obj in objects %} {% block body %}
    <center>
        <div class="col-lg-3 thumbnail">
            <div>{{ obj.uploaded_by }}
                <form action="{% url 'app:delete' obj.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button id="delete">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
            <div>
                <img src="{% static obj.image_url %}" width="300" height="300" />
            </div>
            <div>
                <div>{{ obj.uploaded_at }}</div>
                <div>{{ obj.caption }}</div>
            </div>
            <div>
                <form action="{% url 'app:likes' obj.id %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="fa fa-heart" aria-hidden="true"></i> {{ obj.likes }}
                    </button>
                </form>
                <form action="{% url 'app:filter' obj.id %}" method="get">
                    {% csrf_token %}
                    <button>
                        <i class="fa fa-filter" aria-hidden="true"></i> filter
                    </button>
                </form>
                {% if obj.comments_set.all %}
                <ul>
                    {% for comment in obj.comments_set.all %}
                    <li>
                        {{ comment.comment }} - {{ comment.time }}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form action="{% url 'app:comment' obj.id %}" method="post">
                    {% csrf_token %}{{ c_form }}
                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>
    </center>
    {% endblock body %} {% endfor %}{% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</body>

</html>

app/templates/app/filter.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django View Practice</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
{% block body %}
<center>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">
            <i class="fa fa-upload" aria-hidden="true"></i> Upload</button>
    </form>

    <p>
        <a href="{% url 'app:base' %}">Return to home</a>
    </p>
</center>
{% endblock body %}

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Biopic Login</title>
</head>

<body>
    <center>
        <div id=header>
            <h1>
                <i class="fa fa-picture-o" aria-hidden="true"></i> Biopic </h1>
        </div>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </center>
</body>

</html>

app/templates/app/most_comments.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Biopic Login</title>
</head>

<body>
    <center>
        <div id=header>
            <img src="../../static/app/logo/FullSizeRender.png" />
        </div>
        <br>
        <form action="{% url 'app:base' %}">
            <button>
                <i class="fa fa-home" aria-hidden="true"></i> Home
            </button>
        </form>
        <br>
    </center>
    {% if objects %} {% for obj in objects %} {% block body %}
    <center>
        <div class="col-lg-3 thumbnail">
            <div>
                {{ obj.uploaded_by }}
            </div>
            <div>
                <img src="{% static obj.image_url %}" width="300" height="300" />
            </div>
            <div>
                <div>{{ obj.uploaded_at }}</div>
                <div>{{ obj.caption }}</div>
            </div>
            <div>
                <form action="{% url 'app:likes' obj.id %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="fa fa-heart" aria-hidden="true"></i> {{ obj.likes }}
                    </button>
                </form>
                {% if obj.comments_set.all %}
                <ul>
                    {% for comment in obj.comments_set.all %}
                    <li>
                        {{ comment.comment }} - {{ comment.time }}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form action="{% url 'app:comment' obj.id %}" method="post">
                    {% csrf_token %}{{ c_form }}
                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>
    </center>
    {% endblock %} {% endfor %} {% endif %}
</body>

</html>

app/templates/app/most_like.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Biopic Login</title>
</head>

<body>
    <center>
        <div id=header>
            <h1>
                <i class="fa fa-picture-o" aria-hidden="true"></i> Biopic Top 4 Most Likes </h1>
        </div>
        <br>
        <form action="{% url 'app:base' %}">
            <button>
                <i class="fa fa-home" aria-hidden="true"></i> Home
            </button>
        </form>
        <br>
    </center>
    {% if objects %} {% for obj in objects %} {% block body %}
    <center>
        <div class="col-lg-3 thumbnail">
            <div>
                {{ obj.uploaded_by }}
            </div>
            <div>
                <img src="{% static obj.image_url %}" width="300" height="300" />
            </div>
            <div>
                <div>{{ obj.uploaded_at }}</div>
                <div>{{ obj.caption }}</div>
            </div>
            <div>
                <form action="{% url 'app:likes' obj.id %}" method="post">
                    {% csrf_token %}
                    <button>
                        <i class="fa fa-heart" aria-hidden="true"></i> {{ obj.likes }}
                    </button>
                </form>
            </div>
        </div>
    </center>
    {% endblock %} {% endfor %} {% endif %}
</body>

</html>

app/templates/app/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Biopic Sign up</title>
</head>

<body>
    <center>
        <div id=header>
            <img src="../../static/app/logo/FullSizeRender.png" />
        </div>
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %} {% for field in form %}
            <p>
                {{ field.label_tag }}
                <br> {{ field }} {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
                {% endif %} {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
            {% endfor %}
            <button type="submit">Sign up</button>
        </form>
    </center>
</body>

</html>

app/templates/app/upload.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django View Practice</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
{% block body %}
<center>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">
            <i class="fa fa-upload" aria-hidden="true"></i> Upload</button>
    </form>

    <p>
        <a href="{% url 'app:base' %}">Return to home</a>
    </p>
</center>

{% endblock body %}